# ci.appveyor.com build file ... continuous integration build of xLights for windows on appveyor

# Creates a VM with Visual Studio and pulls xLights and its dependencies and builds it

version: '{build}'

# only build the master branch
branches:
  only:
    - master

os: Visual Studio 2017

# setup multiple build styles
environment:
  matrix:
    # Visual Studio 64 bit debug
    - platform: x64
      configuration: Debug
	# gcc 64 bit release
    - platform: x64
      configuration: 64bit  MinGW_Release
	# gcc 32 bit release
    - platform: x86
      configuration: MinGW_Release
  
notifications:
  - provider: Email
    to:
      - keithsw1111@hotmail.com
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
    
build_script:
  - appveyor.bat
  
# fail as soon as any build fails
matrix:
  fast_finish: true
